### ISSUE TITLE
Comment field presence on submit suggestion screen

### ISSUE THREAD

**Issue by katebanner** [codaco/feedback-site#11]
It strikes me as odd to have the comment field appear before the submit button. It seems to imply that the author of the "suggestion" needs to comment before they can submit, which wouldn't make much sense. Earlier today there was an error message that appeared asking for that field to be completed before the suggestion could be submitted (although it was referred to as the "body", even though the body field had been written in). I can't seem to make it happen again. 
[Feedback system screenshots.pdf](https://github.com/codaco/feedback-site/files/1153949/Feedback.system.screenshots.pdf)

**Comment by jthrilly** [comment]
@katebanner - perhaps I'm not understanding you, but from the looks of things you're talking about replying to a suggestion rather than creating one - is that correct? If so, it makes sense to me to have the existing comment section before the form to post an additional comment.

@meshulam - could we perhaps call this section "discussion"?

**Comment by meshulam** [comment]
@jthrilly "Discussion" makes sense to me. And yeah, the "submit" button is for adding a comment, once you're on that page the main post already exists. So I think the error is just when trying to add a comment without typing anything in.

**Comment by katebanner** [comment]
@jthrilly @meshulam - sorry for the delay. To clarify my initial comment at the top:

The workflow seemed strange to me in that if you, a user/author, create a suggestion, it appears as though you are also required to comment on that suggestion you just created based on the layout of the page.

I ran into an error several times where the system would not let me publish my suggestion without also writing a comment to that suggestion. In the second page of the pdf screenshot I included, a message appears stating that "body is required" even when there was already text in the original "body" of the suggestion.

**Comment by meshulam** [comment]
@katebanner There's a "Post Created" flash when landing on the post page, if you still think it's unclear that you're done submitting when landing on the Post page, can you suggest a UI change to address that?

Otherwise let's close this.

**Comment by jthrilly** [comment]
I agree regarding the general flow, but @meshulam do you have any input on the apparent bug Kate mentions below?

> I ran into an error several times where the system would not let me publish my suggestion without also writing a comment to that suggestion. In the second page of the pdf screenshot I included, a message appears stating that "body is required" even when there was already text in the original "body" of the suggestion.

**Comment by meshulam** [comment]
@katebanner can you describe the steps to reproduce this? It still looks/sounds like you're just clicking "Submit" on the comment form after you've already published your suggestion.

**Comment by katebanner** [comment]
@meshulam I tried to reproduce the bug, but no luck. The pop-up window to submit a new post followed by the "post created" tag appearing at the top of the page seem to address the confusion.

**Comment by meshulam** [comment]
Cool, let me know if you see anything weird. Closing this for now.
