### ISSUE TITLE
New issue flow

### ISSUE THREAD

**Issue by jthrilly** [codaco/feedback-site#12]
The initial idea for the new issue flow called for a wizard.

- Step 1 - log in or continue as guest
Allows the user to choose between two authentication options. Emphasizes the trade offs associated with posting as a guest (no email notifications, mostly).
- Step 2 - title your feedback 
During this step, the user titled their feedback. Here, there is a realtime search happening of existing feedback titles, with fuzzy matching (see https://stackoverflow.com/questions/ask for an example). If matches are returned above a given threshold, they should be shown and suggested to the user as alternative venues for their feedback. Clicking on these titles should open that feedback thread in a new tab.
- Step 3 - Feedback content and tagging

I would still like to see this flow implemented, as I think it has quite a few advantages over what we currently have. At the very least, I think we need to have the fuzzy matching of new titles to existing issues to cut down on potential duplicates and try to streamline discussions.

**Comment by meshulam** [comment]
Opened subtasks for 1 and 2. Can you elaborate on "Step 3 - Feedback content and tagging" in a new ticket if it's still a priority?

**Comment by jthrilly** [comment]
Sorry, my description wasn't clear. Step 3 is basically just "enter the content for the issue". Tagging is done by admins.
