### ISSUE TITLE
New Issue Flow: Login/guest prompt

### ISSUE THREAD

**Issue by meshulam** [codaco/feedback-site#14]
Subtask of #12: Step 1 - log in or continue as guest
Allows the user to choose between two authentication options. Emphasizes the trade offs associated with posting as a guest (no email notifications, mostly).

**Comment by meshulam** [comment]
We already have the guest/user account distinction, this will mostly be UI and copy on top of it.

4-6 hours, dependent on basic UI sketch and copy. Or I can stub that out and leave styling to you.

**Comment by jthrilly** [comment]
Leave UI to me, here.
