### ISSUE TITLE
Category selection

### ISSUE THREAD

**Issue by pfsj** [codaco/feedback-site#17]
When you select any category other than "All Categories" in the category selection drop down, the drop down does not collapse back. I think we want this to collapse after selecting a category?

**Comment by jthrilly** [comment]
The "sort" dropdown closes itself after I select something, but the "Categories" only closes itself if I select "All Categories". Perhaps that was intentional since there isn't any other indication that you're only seeing some of the posts, but that "indication" goes away when you click elsewhere.

**Comment by meshulam** [comment]
This was a bug, it's been fixed. Thanks!
