### ISSUE TITLE
profile name change and hardcoded URL

### ISSUE THREAD

**Issue by berniehogan** [codaco/feedback-site#23]
So when I changed my name from bhogantest to bhogan this changed the display name. There were a few weird artifacts but they disappeared after a refresh. However, my profile is still 
https://feedback.networkcanvas.com/users/bhogantest

and not

https://feedback.networkcanvas.com/users/bhogan

**Comment by meshulam** [comment]
As you noticed, the editable displayName is a separate field from the (non-modifiable) username. The intention of displayName is to support firstname/lastname: spaces, and other special characters that aren't allowed in a username. The profile URL is based on the username, not the displayName.

What if we just show the username as a non-editable field on the edit form so it's clearer what you're actually changing?

**Comment by jthrilly** [comment]
I think that works (I see you already did it, just wanted to confirm).

**Comment by meshulam** [comment]
Yep, decided to go ahead with that approach. Closing this, though feel free to reopen if there's other ideas.
