### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by meshulam** [codaco/feedback-site#3]
Try to use same bootstrap theme as the main NetworkCanvas site?

**Comment by jthrilly** [comment]
Could be tricky, but if you can get something rudimentary up, I will tweak it.

You mentioned this is react based. We actually have a UI component repo that is implementing some of our project style guide. Check out https://github.com/codaco/Network-Canvas-UI

If any of those components can be used again (perhaps only the utilities such as colors and typography), please go ahead.

**Comment by meshulam** [comment]
Deployed a first pass styling with the Network Canvas font and color scheme. The existing styles are a bit of a hybrid bootstrap and custom CSS, I started moving toward more pure bootstrap. SASS source is here: https://github.com/codaco/feedback-site/tree/master/packages/networkcanvas-styles/lib/stylesheets
