### ISSUE TITLE
Password reset/account recovery

### ISSUE THREAD

**Issue by meshulam** [codaco/feedback-site#4]
Use MailChimp or the Network Canvas Gmail account for sending out reset emails?

**Comment by berniehogan** [comment]
Either should work. Path of least resistance. Google gmail accounts can be given app specific passwords for such things. I've done it in python with little fuss.

**Comment by meshulam** [comment]
Got the email send working with Gmail, still working on a bug with the actual reset form.

**Comment by jthrilly** [comment]
Actually, the gmail account is not supposed to be used, generally. Can we do this with info@networkcanvas.com? We can set up a legitimate mailbox with a new name (such as feedback-forum@networkcanvas.com), and provide smtp details. What would you need to make this work?

**Comment by meshulam** [comment]
We can use any email address as long as there's a username/password for SMTP. So the @networkcanvas.com addresses should work fine.

**Comment by jthrilly** [comment]
Brilliant.

**Comment by meshulam** [comment]
Just need to get the SMTP credentials for this to work.

Do you guys have a shared secret store like LastPass? Would be useful for some of the other deployment stuff too.

**Comment by jthrilly** [comment]
We actually don't. Can you message me on slack to try and get this set up? Afraid I am not too knowledgeable about it.

**Comment by meshulam** [comment]
The feedback site is now sending password reset emails from info@networkcanvas.com.
