### ISSUE TITLE
Decide on noun to use for suggestions

### ISSUE THREAD

**Issue by meshulam** [codaco/feedback-site#6]
Suggestion, Issue, Post, other?

**Comment by berniehogan** [comment]
I prefer "post" as it is non-specific. People might have comments, questions or ideas. We cannot tell ahead of time if it will be a comment or a suggestion. Also, for use in other places like "no more suggestions" at the bottom of the search box results, the word suggestions there is peculiar. Having the word posts makes sense. But "no more posts " would be even clearer.

**Comment by meshulam** [comment]
Updated to "Post," I agree it's the least confusing. Let's close this if that's the consensus.

**Comment by jthrilly** [comment]
Post seems to make sense.
