### ISSUE TITLE
Admin-specific formatting

### ISSUE THREAD

**Issue by meshulam** [codaco/feedback-site#7]
Do admins need to be able to Import/export suggestions, or view suggestions in any format besides the standard navigation?

**Comment by berniehogan** [comment]
I don't think that's especially important right now. We might come into problems later, but new ways to sort is not going to create any problematic path dependencies. So this to me is less important.

**Comment by jthrilly** [comment]
The only one I can think of would be a view that lets us see unresolved/unreplied to threads.

**Comment by meshulam** [comment]
Going to close this for now. The framework has some admin views already.
